module.exports = {
  "Babel JSX package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web",
    "eslint",
    "eslint-es6",
    "eslint-jsx",
    "husky",
    "jest",
    "jest-babel",
    "jest-browser",
    "jest-scripts",
  ],
  "Babel package": [
    "basics",
    "babel",
    "babel-node",
    "babel-scripts",
    "eslint",
    "eslint-es6",
    "husky",
    "jest",
    "jest-babel",
    "jest-node",
    "jest-scripts",
  ],
  "ES6 package": [
    "basics",
    "eslint",
    "husky",
    "jest",
    "jest-node",
    "jest-scripts",
  ],
  "Typescript package": [
    "basics",
    "eslint",
    "eslint-typescript",
    "husky",
    "jest",
    "jest-typescript",
    "jest-scripts",
    "typescript",
  ],
}
